export const questions = [
  {
    questionName: "Q1",
    question: "How many continents are there on earth?",
    solution: "7",
    answers: ["7", "5", "4", "10"],
    correct: null,
  },
  {
    questionName: "Q2",
    question: "In which continent is the Netherlands located?",
    solution: "Europe",
    answers: ["Asia", "Europe", "North America", "Oceana"],
    correct: null,
  },
  {
    questionName: "Q3",
    question: "What is the Netherlands language?",
    solution: "Dutch",
    answers: ["French", "Dutch", "Flemish", "Afrikaans"],
    correct: null,
  },
  {
    questionName: "Q4",
    question: "Name the capital of the Netherlands",
    solution: "Amsterdam",
    answers: ["The Hague", "Brussels", "Antwerp", "Amsterdam"],
    correct: null,
  },
  {
    questionName: "Q5",
    question: "What is the currency of the Netherlands?",
    solution: "EUR",
    answers: ["PHP", "USD", "EUR", "NOK"],
    correct: null,
  },

  {
    questionName: "Q6",
    question: "In which continent is Australia located?",
    solution: "Oceania",
    answers: ["Australia", "Asia", "Europe", "Oceania"],
    correct: null,
  },
  {
    questionName: "Q7",
    question: "What is the currency of Australia?",
    solution: "AUD",
    answers: ["ALL", "AUD", "USD", "AMD"],
    correct: null,
  },
  {
    questionName: "Q8",
    question: "Which country is in Asia?",
    solution: "Kuwait",
    answers: ["Aruba", "Bulgaria", "Cyprus", "Kuwait"],
    correct: null,
  },
  {
    questionName: "Q9",
    question: "Which country is not in Oceania?",
    solution: "Bahamas",
    answers: ["New Zealand", "Fiji", "French Polynesia", "Bahamas"],
    correct: null,
  },
  {
    questionName: "Q10",
    question: "which is not a language of Belgium?",
    solution: "Malay",
    answers: ["Dutch", "French", "Malay", "German"],
    correct: null,
  },

  {
    questionName: "Q11",
    question: "Name the capital of Bermuda",
    solution: "Hamilton",
    answers: ["Vienna", "Amsterdam", "Hamilton", "Minsk"],
    correct: null,
  },
  {
    questionName: "Q12",
    question: "In which continent is Russia located?",
    solution: "Europe",
    answers: ["Europe", "Asia", "Oceania", "South America"],
    correct: null,
  },
  {
    questionName: "Q13",
    question: "Name the capital of Belarus",
    solution: "Minsk",
    answers: ["Vienna", "Minsk", "Moscow", "Ottawa"],
    correct: null,
  },
  {
    questionName: "Q14",
    question: "Name the capital of Russia?",
    solution: "Moscow",
    answers: ["Minsk", "Ottawa", "Moscow", "Vienna"],
    correct: null,
  },
  {
    questionName: "Q15",
    question: "Name the capital of Canada",
    solution: "Ottawa",
    answers: ["Ottawa", "Vienna", "Bridgetown", "London"],
    correct: null,
  },
];
