export const questions = [
  {
    questionName: "Q1",
    question: "How many continents are there?",
    solution: "7",
    answers: ["7", "5", "4", "10"],
    correct: null,
  },
  {
    questionName: "Q2",
    question: "On which continent is the Netherlands?",
    solution: "Europe",
    answers: ["Asia", "Europe", "North America", "Oceana"],
    correct: null,
  },
  {
    questionName: "Q3",
    question: "What is the Netherland's language",
    solution: "Dutch",
    answers: ["French", "Dutch", "Flemish", "Afrikaans"],
    correct: null,
  },
  {
    questionName: "Q4",
    question: "What is the capital of the Netherlands",
    solution: "Amsterdam",
    answers: ["The Hague", "Brussels", "Antwerp", "Amsterdam"],
    correct: null,
  },
  {
    questionName: "Q5",
    question: "What is the Netherlands' currency?",
    solution: "EUR",
    answers: ["PHP", "USD", "EUR", "NOK"],
    correct: null,
  },

  {
    questionName: "Q6",
    question: "On which continent is Australia?",
    solution: "Oceania",
    answers: ["Australia", "Asia", "Europe", "Oceania"],
    correct: null,
  },
  {
    questionName: "Q7",
    question: "What is the curreny of Australia",
    solution: "AUD",
    answers: ["ALL", "AUD", "USD", "AMD"],
    correct: null,
  },
  {
    questionName: "Q8",
    question: "What country is in Asia",
    solution: "Kuwait",
    answers: ["Aruba", "Bulgaria", "Cyprus", "Kuwait"],
    correct: null,
  },
  {
    questionName: "Q9",
    question: "What country is not in Oceania?",
    solution: "Bahamas",
    answers: ["New Zealand", "Fiji", "French Polynesia", "Bahamas"],
    correct: null,
  },
  {
    questionName: "Q10",
    question: "what are not the languages of Belgium?",
    solution: "Malay",
    answers: ["Dutch", "French", "Malay", "German"],
    correct: null,
  },

  {
    questionName: "Q11",
    question: "What the capital of Bermuda?",
    solution: "Hamilton",
    answers: ["Vienna", "Amsterdam", "Hamilton", "Minsk"],
    correct: null,
  },
  {
    questionName: "Q12",
    question: "On which continent is Russia?",
    solution: "Europe",
    answers: ["Europe", "Asia", "Oceania", "South America"],
    correct: null,
  },
  {
    questionName: "Q13",
    question: "what is the capital of Belarus?",
    solution: "Minsk",
    answers: ["Ottawa", "Minsk", "Moscow", "Vienna"],
    correct: null,
  },
  {
    questionName: "Q14",
    question: "what is the capital of Russia?",
    solution: "Moscow",
    answers: ["Ottawa", "Minsk", "Moscow", "Vienna"],
    correct: null,
  },
  {
    questionName: "Q15",
    question: "What is the capital of Canada",
    solution: "Ottawa",
    answers: ["Ottawa", "Vienna", "Bridgetown", "London"],
    correct: null,
  },
];
